name: sidharth
description: "A portfolio"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.4
  animated_flip_counter: ^0.3.4
  animate_do: ^3.3.4
  rive: ^0.13.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/jpeg/
    - assets/images/png/
    - assets/rives/

  fonts:
    - family: Elgoc-Thin
      fonts:
        - asset: assets/font/Elgoc-Thin.otf
    - family: CindieMono-D
      fonts:
        - asset: assets/font/CindieMono-D.otf
