name: sidharth
description: "Personal Portfolio built with Flutter Web"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.4
  animate_do: ^3.3.4
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.17
  dotted_border: ^2.1.0
  http: ^1.4.0
  animated_flip_counter: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env.json
    - assets/images/jpeg/
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Elgoc-Thin
      fonts:
        - asset: assets/font/Elgoc-Thin.otf
    - family: CindieMono-D
      fonts:
        - asset: assets/font/CindieMono-D.otf
