name: sidharth
description: "Personal Portfolio built with Flutter Web"
publish_to: "none"
version: 0.5.40

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^4.2.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.1.0
  dotted_border: ^3.0.1
  http: ^1.4.0
  web: ^1.1.1
  animated_flip_counter: ^0.3.4
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/jpeg/
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Elgoc-Thin
      fonts:
        - asset: assets/font/Elgoc-Thin.otf
    - family: CindieMono-D
      fonts:
        - asset: assets/font/CindieMono-D.otf
